* Kwin effect smart invert
Intelligently inverts windows by applying a shader that preserves colors other than black and white By Default. Exactly like the default invert [[https://github.com/KDE/kwin/tree/master/effects/invert][plugin]] provided by KDE except it allows custom shaders.
** Custom shaders
Shader files can be set in =/usr/share/kwin/shaders/1.40=. The file with name =invert.frag= will be selected. Turning the plugin off then back on within KWin effects will apply the new shader.
Application comes with a few well selected shaders. The default being [[file:data/1.40/invert.frag.log69.cpp]] since it looks the best.
** Default Shortcuts
- Inverting the entire screen ::
=SHIFT + CTRL + META + Z=  
- Inverting the current window ::
=CTRL + META + Z= 

You can change the shortcuts via System Settings -> Global Keyboard Shortcuts -> KWin
Or directly from the kwin effects settings menu.
** Dependencies
I haven't tested these dependencies. refer to [[https://github.com/ugjka/kwin-,ileffect-grayscale][this]] and [[https://github.com/alex47/KDE-Rounded-Corners][this]] repos.
- Arch based ::
You need extra-cmake-modules, kwin and kf5 *-dev packages installed
- Debian based (Ubuntu, Kubuntu, KDE Neon) ::
#+begin_src bash
sudo apt install git cmake g++ gettext extra-cmake-modules qttools5-dev libqt5x11extras5-dev libkf5configwidgets-dev libkf5crash-dev libkf5globalaccel-dev libkf5kio-dev libkf5notifications-dev kinit-dev kwin-dev 
#+end_src
- Fedora based ::
#+begin_src bash

sudo dnf install git cmake gcc-c++ extra-cmake-modules qt5-qttools-devel qt5-qttools-static qt5-qtx11extras-devel kf5-kconfigwidgets-devel kf5-kcrash-devel kf5-kguiaddons-devel kf5-kglobalaccel-devel kf5-kio-devel kf5-ki18n-devel kf5-knotifications-devel kf5-kinit-devel kwin-devel qt5-qtbase-devel libepoxy-devel

#+end_src
** Building
#+begin_src bash
git clone https://github.com/natask/kwin-effect-smart-invert.git
cd kwin-effect-smart-invert
mkdir -p build && cd build
cmake .. && make && sudo make install && (kwin_x11 --replace &)
#+end_src

#+RESULTS:

** inspirations
- Plugin  ::
  - [[https://github.com/KDE/kwin/tree/master/effects/invert]]
  - [[https://github.com/ugjka/kwin-effect-grayscale]]
  - [[https://www.reddit.com/r/kde/comments/hscf6f/attempting_to_write_smart_inversion_effect_for_kde/]]
  - [[https://github.com/alex47/KDE-Rounded-Corners]]
- Shaders ::
  - https://github.com/vn971/linux-color-inversion
  - https://github.com/mlaily/NegativeScreen
  - https://github.com/natask/gnome_invert_windows/blob/master/extension.js
  - https://github.com/maiself/gnome-shell-extension-invert-color/issues/1

** TODOs
*** TODO Plugin breaks when started on by default
*** TODO Start inverted
*** TODO What is the point of duplicated declarations for keybindings in [[file:invert.cpp]] and [[file:invert_config.cpp]]. 
*** TODO Change internal naming from kwin-effect-smartInvert to kwin-effect-smart-invert
*** TODO User level plugins
*** TODO Hot swap shader files.
*** TODO Window allow and deny lists.
