* Kwin effect smart invert
Intelligently inverts windows by applying a shader that preserves colors other than black and white By Default. Exactly like the default invert [[https://github.com/KDE/kwin/tree/master/effects/invert][plugin]] provided by KDE except it allows custom shaders.
** Custom shaders
Shader files can be set in =/usr/share/kwin/shaders/1.40=. The file with name =invert.frag= will be selected. Turning the plugin off then back on within KWin effects will apply the new shader.
Application comes with a few well selected shaders. The default being [[file:data/1.40/invert.frag.log69.cpp]] since it looks the best.
** Default Shortcuts
:PROPERTIES:
:ID:       21ab3fc5-3b89-43dc-b81c-ac42309efc24
:END:
- Inverting the entire screen ::
=SHIFT + CTRL + META + Z=  
- Inverting the current window ::
=CTRL + META + Z= 

You can change the shortcuts via System Settings -> Global Keyboard Shortcuts -> KWin
Or directly from the kwin effects settings menu.
** Features
:PROPERTIES:
:ID:       947c4ab3-9cf6-4d99-9a7b-f7893ddd9cb0
:END:
:LOGBOOK:
- Newly Created           [2021-09-26 Sun 00:33:31]
:END:
- Hot Swap ::
  + change shader file by following [[Custom shaders]]
  + invert a window to try out shader without affecting all windows.
  + invert the entire screen to apply new shader to all windows.
- Block list ::
  + window classes added to blocklist in kde system settings effect configuration are not inverted.
  + Use `xprop WM_CLASS` or `wmctrl -lx` and take the second string to get window class. For example =xprop WM_ClASS= returns =M_CLASS(STRING) = "systemsettings5", "systemsettings"= for a system settings window. Take the second string, ="systemsettings"= and place in blocklist.
  + Case insensitive.
  + Separate window classes with comma. E.g: =discord,emacs=.
** Dependencies
I haven't tested these dependencies. refer to [[https://github.com/ugjka/kwin-,ileffect-grayscale][this]] and [[https://github.com/alex47/KDE-Rounded-Corners][this]] repos.
- Arch based ::
#+begin_src bash
sudo pacman -S extra-cmake-modules kwin kf5
#+end_src
- Debian based (Ubuntu, Kubuntu, KDE Neon) ::
#+begin_src bash
sudo apt install git cmake g++ gettext extra-cmake-modules qttools5-dev libqt5x11extras5-dev libkf5configwidgets-dev libkf5crash-dev libkf5globalaccel-dev libkf5kio-dev libkf5notifications-dev kinit-dev kwin-dev 
#+end_src
- Fedora based ::
#+begin_src bash

sudo dnf install git cmake gcc-c++ extra-cmake-modules qt5-qttools-devel qt5-qttools-static qt5-qtx11extras-devel kf5-kconfigwidgets-devel kf5-kcrash-devel kf5-kguiaddons-devel kf5-kglobalaccel-devel kf5-kio-devel kf5-ki18n-devel kf5-knotifications-devel kf5-kinit-devel kwin-devel qt5-qtbase-devel libepoxy-devel

#+end_src
** Building
#+begin_src bash
git clone https://github.com/natask/kwin-effect-smart-invert.git
cd kwin-effect-smart-invert
mkdir -p build && cd build
cmake .. && make && sudo make install && (kwin_x11 --replace &)
#+end_src

#+RESULTS:

** inspirations
- Plugin  ::
  - [[https://github.com/KDE/kwin/tree/master/effects/invert]]
  - [[https://github.com/ugjka/kwin-effect-grayscale]]
  - [[https://www.reddit.com/r/kde/comments/hscf6f/attempting_to_write_smart_inversion_effect_for_kde/]]
  - [[https://github.com/alex47/KDE-Rounded-Corners]]
- Shaders ::
  - https://github.com/vn971/linux-color-inversion
  - https://github.com/mlaily/NegativeScreen
  - https://github.com/natask/gnome_invert_windows/blob/master/extension.js
  - https://github.com/maiself/gnome-shell-extension-invert-color/issues/1

** TODOs
*** TODO Window pass lists.
:PROPERTIES:
:ID:       30387191-1d41-45c7-a551-c7d379e01085
:END:
:LOGBOOK:
- State "TODO"       from              [2021-10-21 Thu 10:57:31 PDT]
- Newly Created           [2021-10-21 Thu 10:57:19 PDT]
:END:
*** TODO What is the point of duplicated declarations for keybindings in [[file:invert.cpp]] and [[file:invert_config.cpp]].
:PROPERTIES:
:ID:       bb82c42b-eaea-4f02-bbeb-0050736469e7
:END:
*** DONE Auto Start inverted
:LOGBOOK:
- State "DONE"       from "NEXT"       [2021-09-25 Sat 20:53:42]
:END:
*** DONE Change internal naming from kwin-effect-smartInvert to kwin-effect-smart-invert
:LOGBOOK:
- State "DONE"       from "NEXT"       [2021-09-25 Sat 20:54:16]
:END:
*** DONE Hot swap shader files.
:LOGBOOK:
- State "DONE"       from "NEXT"       [2021-09-25 Sat 21:00:30]
:END:
*** DONE Window block lists.
:PROPERTIES:
:ID:       237558a9-924a-4f77-abcc-6d781d4ddf37
:END:
:LOGBOOK:
- State "DONE"       from "NEXT"       [2021-10-21 Thu 10:57:17 PDT]
:END:
*** DONE User level plugins
:LOGBOOK:
- State "DONE"       from "NEXT"       [2021-10-21 Thu 10:57:45 PDT]
:END:
I beleve I have already implemented this. It required modifying CMakeList.txt.
